version: "3.9"

services:
  web:
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./docker/web/Dockerfile
    env_file: .env
    ports:
      - ${PORT}:${PORT}
    networks:
      - service-network
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./docker/db/Dockerfile
    env_file: .env
    ports:
      - ${DB_PORT}:${DB_PORT}
    networks:
      - service-network
    volumes:
      - dbdata:/var/lib/postgresql/data

networks:
  service-network:
    driver: bridge


volumes:
  dbdata:
